version: '3.9'

services:
    snmp-agent:
        build:
            context: ./agent
        container_name: snmp-agent
        ports:
            - '161:161/udp'
        networks:
            - snmp-net

    trap-receiver:
        build:
            context: ./trap-receiver
        container_name: snmp-trap-receiver
        ports:
            - '162:162/udp'
            - '163:163/udp'
        networks:
            - snmp-net

networks:
    snmp-net:
        driver: bridge
